### PR TITLE
AE/technology partners neura nov 19

### PR DESCRIPTION
**Pull request by adischik**
# Pull Request/Issue Resolution

**Description of Change:**
> I'm changing the file name I previously changed to its original name to align with links external to the docs so that they won't be broken links anymore. I also changed the crop size of an image I prviously uploaded

**Reason for Change:**
> I'm making this change because I found that the file name change broke the link on the Alloys page.

Closes #**ISSUE_NUMBER_HERE**

### Is this change associated with a Braze feature/product release?
- [ ] Yes (__Feature Release Date:__)
- [ ] No

> If yes, please note the date of the feature release.

---
---

## PR Checklist
- [ ] Ensure you have completed [our CLA](https://www.braze.com/docs/cla/).
- [ ] Tag @EmilyNecciai as a reviewer when your work is _done and ready to be reviewed for merge_.
- [ ] Consult the [Docs Text Formatting Guide](https://github.com/Appboy/success/wiki/Docs-Text-Formatting-Guide).
- [ ] Consult the [Docs Writing Style Guide & Best Practices](https://github.com/Appboy/success/wiki/Writing-Style-Guide-&-Best-Practices).
- [ ] Tag others as Reviewers as necessary.
- [ ] If you have modified any links, be sure to add redirects to `config/nginx.conf.erb`.

## ATTENTION: REVIEWERS OF THIS PR
- [ ] Read our [Reviewing a PR page](https://github.com/Appboy/braze-docs/wiki/Reviewing-a-PR) for more on our reviewing suggestions.
- [ ] Preview all changes in the linked Heroku environment (click `View deployment` button below, then "Docs". A `502` error just means you should refresh until you see the Docs Home page.
---
---

### CODE REVIEW

**Comment by adischik** [comment]
Hi @EmilyNecciai! I'm not able to add you as a reviewer directly, I hope that this comment will suffice. Thanks!

**Comment by EmilyNecciai** [comment]
@adischik Hi! I think I might just redirect the old link to one of the new ones - is there a preference of where `/partners/neura/` should go? (i.e to the insights page or the actions page?)

**Comment by EmilyNecciai** [comment]
Fixed with a redirect! Thank you @adischik !

**Comment by adischik** [comment]
Hi @EmilyNecciai! Thank you for your continued help! I would really prefer to submit the pull request for merging though. Mostly because I also added a few content changes (updated and image, added a link back to the insights page). On top of that, there is still the link from Alloys and another link from the docs that don't work for me. I'm guessing that there are other links out there so just renaming the file back to its original name (neura.md) seems like the safest solution. Sorry for causing trouble! Thanks again!

**Comment by EmilyNecciai** [comment]
No worries @adischik !! :)

I duplicated your changes to the file here: #641 

I also added in another redirect which will hopefully solve all the issues without changing the file name and causing other issues on our end. :) 

Reach out if anything still isn't resolved! Thank you! 🎉

**Pull request closed without merging**
