### PR TITLE
Update push_ttl_settings.md

### PR DESCRIPTION
**Pull request by davidbielik**
* removed outdated note on default TTL
* added note on what TTL does

### CODE REVIEW

**Review by chrishaines — APPROVED** [review]
Looks good. Do we want to also update the image because the copy is slightly different?

**Comment by davidbielik** [comment]
> Looks good. Do we want to also update the image because the copy is slightly different?

Yep, i'll do that too, thanks

**Comment by chrishaines** [comment]
> > Looks good. Do we want to also update the image because the copy is slightly different?
> 
> Yep, i'll do that too, thanks

Cool. The change is currently deploying to Sweeney so you might want to wait a few minutes for it to finish rolling out.

**Review by timothy-kim — APPROVED** [review]
👍

**Pull request merged**
