### PR TITLE
Added Vizbee partner documents

### PR DESCRIPTION
**Pull request by maxqper**
# Pull Request/Issue Resolution

**Description of Change:**
Added Vizbee partner documentation for TV deep linking.

Closes  #NOT_APPLICABLE

### Is this change associated with a Braze feature/product release?
- [ ] Yes (__Insert Feature Release Date Here__)
- [X] No

> If yes, please note the date of the feature release.

---
---

<details>
<summary>PR Checklist</summary>

- [x] Check that all links work!
- [x] Ensure you have completed [our CLA](https://www.braze.com/docs/cla/).
- [ ] Tag @Timothy-Kim and @KellieHawks as a reviewer when your work is _done and ready to be reviewed for merge_.
- [x] Tag others as Reviewers as necessary.
- [x] If you have modified any links, be sure to add redirects to `config/nginx.conf.erb`.

</details>

<details>
<summary>Writing & Style Quick Tips</summary>

- Use the formatting shown on the [Styling Test Page](https://github.com/Appboy/braze-docs/blob/develop/_docs/_home/styling_test_page.md) to create unique templates and vehicles for your information.
- Use Action verbs!
- Capitalize proper nouns, unique Braze tools and features, custom Braze channels, and all Header titles.
- Redirect when necessary!
- Always speak to the Braze customer - refer to them as “you”, whether they are an Engineer/Developer, a Marketer, or an Admin.
- On Voice: You should aim to be a Friendly Professor. Imagine, if you will, the smartest, but also kindest professor you had. You know, the one who showed you your potential and tested you, but also went slowly in class so you could take great notes and learn some things? Don't be too peppy, but don't be formal. You’re not selling anything - you’re instructing and informing and enabling.

_Consult the [Docs Text Formatting Guide](https://github.com/Appboy/braze-docs/wiki/Special-Formatting) and the [Docs Writing Style Guide & Best Practices](https://github.com/Appboy/braze-docs/wiki/Writing-Style-Guide-&-Best-Practices) for more details._

</details>

<details>
<summary>ATTENTION: For PR Reviewers</summary>

- [ ] Read our [Reviewing a PR page](https://github.com/Appboy/braze-docs/wiki/Reviewing-a-PR) for more on our reviewing suggestions.
- [ ] Preview all changes in the linked Heroku environment (click `View deployment` button below, then "Docs". A `502` error just means you should refresh until you see the Docs Home page.
</details>

---
---

### CODE REVIEW

**Comment by maxqper** [comment]
@timothy-kim @KellieHawks

**Comment by KellieHawks** [comment]
@cla-bot check

**Comment by KellieHawks** [comment]
Hey @maxqper, thanks for contributing to the Braze docs. I was wondering if you'd be able to toggle on the "Allow edits by maintainers" option that can be found on this page. This will allow the docs team here to freely edit your PR.

[Information on how to toggle this on can be found here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)

Please let me know if any problems arise. Thanks again!
The Braze Documentation team

**Comment by maxqper** [comment]
> Hey @maxqper, thanks for contributing to the Braze docs. I was wondering if you'd be able to toggle on the "Allow edits by maintainers" option that can be found on this page. This will allow the docs team here to freely edit your PR.
> 
> [Information on how to toggle this on can be found here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)
> 
> Please let me know if any problems arise. Thanks again!
> The Braze Documentation team

@KellieHawks -- maybe github changed the UI but we do not see the toggle to "allow edits by maintainers". Any advice on what we're missing?

**Comment by KellieHawks** [comment]
@maxqper 

Ahh, I see. Thanks for bearing with us as we get our partner documentation process ironed out. We are currently looking into why some partners haven't been able to find this option. 

As a workaround, since I do not have write permissions, I have created a new [PR](https://github.com/Appboy/braze-docs/pull/1289) with the appropriate changes. I will tag you in it for visibility, and close this PR. Right now we are waiting on the partner team to finish creating your partnership tile and will add this info to our repo once we get that confirmation. Thanks!

The Braze Documentation Team.

**Pull request closed without merging**
