### PR TITLE
Leftovers - December 6, 2019

### PR DESCRIPTION
**Pull request by EmilyNecciai**
# Content 
#728 - Moved the TLS Deprecation Docs to the Deprecation Section. 
#736 - Updated info on being unable to add steps between already existing steps in a launced Canvas. 
#738 - Updated Pump version
#731 - Updated mParticle Page
#732 - Updated iOS custom integration docs.
#708 - iOS in-app message customization: you can now force hide the status bar.

# Features
#729 - Updated SEO options with new tags. 
#733 - Updating IP and Domains page with new Templates & metadata
#730 - Updated Metadata standards guide
#734 - Added Table of Contents to Split Video Layout Template
#739 - Removed `edit on Github` button from above table of contents on Split Video Layout Template. 
#741 - Table of Contents adjustments.
#737 - Added metadata to SDK Changelog pages. 
#735 - Added metadata to Segments pages
#740 - Removed show of H1 Headers from Table of Contents. 
#742 - Issue and PR templates adjusted.

### CODE REVIEW

**Comment by EmilyNecciai** [comment]
@cla-bot check

**Comment by zzhaobraze** [comment]
@cla-bot check

**Comment by zzhaobraze** [comment]
@cla-bot check

**Comment by EmilyNecciai** [comment]
@cla-bot check

**Comment by EmilyNecciai** [comment]
@cla-bot check

**Pull request merged**
