### PR TITLE
Neura partnership integration documentation updates and additions

### PR DESCRIPTION
**Pull request by adischik**
# Pull Request/Issue Resolution

**Description of Change:**
> I'm changing the Neura integration docs on the Technological Partners section

**Reason for Change:**
> I'm making this change because of two things: first, there were changes and clarifications needed to make the integration itself simpler and better. Second, I split our documentation to make our offering fit into the right categories set by the structure of the documentation pages.

### Is this change associated with a Braze feature/product release?
- [ ] Yes (__Feature Release Date:__)
- [ ] No

> If yes, please note the date of the feature release.

---
---

## PR Checklist
- [ ] Ensure you have completed [our CLA](https://www.braze.com/docs/cla/).
- [ ] Tag @EmilyNecciai as a reviewer when your work is _done and ready to be reviewed for merge_.
- [ ] Consult the [Docs Text Formatting Guide](https://github.com/Appboy/success/wiki/Docs-Text-Formatting-Guide).
- [ ] Consult the [Docs Writing Style Guide & Best Practices](https://github.com/Appboy/success/wiki/Writing-Style-Guide-&-Best-Practices).
- [ ] Tag others as Reviewers as necessary.
- [ ] If you have modified any links, be sure to add redirects to `config/nginx.conf.erb`.

## ATTENTION: REVIEWERS OF THIS PR
- [ ] Read our [Reviewing a PR page](https://github.com/Appboy/braze-docs/wiki/Reviewing-a-PR) for more on our reviewing suggestions.
- [ ] Preview all changes in the linked Heroku environment (click `View deployment` button below, then "Docs". A `502` error just means you should refresh until you see the Docs Home page.
---
---

### CODE REVIEW

**Comment by zzhaobraze** [comment]
@cla-bot check

**Comment by zzhaobraze** [comment]
@cla-bot check

**Comment by zzhaobraze** [comment]
@cla-bot check

**Comment by zzhaobraze** [comment]
@cla-bot check

**Comment by zzhaobraze** [comment]
@adischik sorry for the spam, it looks like the cla-bot check is having a slight issue at the moment. We're looking into it, and it should be fixed shortly.

**Comment by EmilyNecciai** [comment]
@cla-boy check

**Comment by EmilyNecciai** [comment]
@cla-bot check

**Pull request merged**
