### PR TITLE
Add setLanguage to web SDK

### PR DESCRIPTION
**Pull request by wesleyorbin**

### CODE REVIEW

**Comment by KellieHawks** [comment]
@wesleyorbin Checking if this draft is ready for review, would love to add it to docs today if possible.

**Comment by wesleyorbin** [comment]
Hi @KellieHawks! We haven't released it on the Web SDK yet, so it's not ready to merge.

**Comment by KellieHawks** [comment]
Sound good! Thanks for the update

**Comment by wesleyorbin** [comment]
Hi @KellieHawks! We just released 2.6.0 so this change is ready to be merged.

**Pull request merged**
