### PR TITLE
Update integration.md

### PR DESCRIPTION
**Pull request by danlourenco**
Typo in argument to `appboy.display.showInAppMessage`

# Pull Request/Issue Resolution

**Description of Change:**
> I'm changing a code snippet here: https://www.braze.com/docs/developer_guide/platform_integration_guides/web/push_notifications/integration/#integration

**Reason for Change:**
> I'm making this change because there's a typo that may confuse users

Closes #**ISSUE_NUMBER_HERE**

### Is this change associated with a Braze feature/product release?
- [ ] Yes (__Feature Release Date:__)
- [ ] No

> If yes, please note the date of the feature release.

---
---

## PR Checklist
- [x] Ensure you have completed [our CLA](https://www.braze.com/docs/cla/).
- [ ] Tag @EmilyNecciai as a reviewer when the your work is _done and ready to be reviewed for merge_.
- [ ] Consult the [Docs Text Formatting Guide](https://github.com/Appboy/success/wiki/Docs-Text-Formatting-Guide).
- [ ] Consult the [Docs Writing Style Guide & Best Practices](https://github.com/Appboy/success/wiki/Writing-Style-Guide-&-Best-Practices).
- [ ] Tag others as Reviewers as necessary.
- [ ] If you have modified any links, be sure to add redirects to `config/nginx.conf.erb`.

## ATTENTION: REVIEWERS OF THIS PR
- [ ] Read our [Reviewing a PR page](https://github.com/Appboy/braze-docs/wiki/Reviewing-a-PR) for more on our reviewing suggestions.
- [ ] Preview all changes in the linked Heroku environment (click `View deployment` button below, then "Docs". A `502` error just means you should refresh until you see the Docs Home page.
---
---

### CODE REVIEW

**Comment by EmilyNecciai** [comment]
@froodian Can you confirm this correction? Thanks!

**Comment by EmilyNecciai** [comment]
Thank you!

**Comment by EmilyNecciai** [comment]
@cla-bot check

**Comment by EmilyNecciai** [comment]
@danlourenco Could you please sign our CLA? Thank you! https://www.braze.com/docs/cla/

**Comment by danlourenco** [comment]
@EmilyNecciai sorry for the delay! I've now signed the CLA

**Comment by EmilyNecciai** [comment]
@cla-bot check

**Pull request merged**
