### PR TITLE
inkit data fields update

### PR DESCRIPTION
**Pull request by dkim32**
# Pull Request/Issue Resolution

**Description of Change:**
- optional data fields 
- added note about custom data fields 
- formatting for authorization HTTP header values 

**Reason for Change:**
ensure that customers are aware of optional data fields and custom data fields.

Closes #**ISSUE_NUMBER_HERE**

---
---

## PR Checklist
- [ ] Ensure you have completed our CLA.
- [ ] Tag @EmilyNecciai as a reviewer when the your work is done and ready to be reviewed for merge. 
- [ ] Consult the [Docs Text Formatting Guide](https://github.com/Appboy/success/wiki/Docs-Text-Formatting-Guide) to be sure you're utilizing the proper markdown formatting.
- [ ] Consult the [Docs Writing Style Guide & Best Practices](https://github.com/Appboy/success/wiki/Writing-Style-Guide-&-Best-Practices) to be sure you're aligning with our voice and other style best practices.
- [ ] [Preview your deployed changes](https://homeslice.braze.com/docs) to confirm that none of your changes break production. Pay close attention to links and images.
- [ ] Tag others as Reviewers as necessary.
- [ ] If you have modified any links, be sure to add redirects to `config/nginx.conf.erb`.

---
---

### CODE REVIEW

**Comment by dkim32** [comment]
@EmilyNecciai - if you have time, this can go out this week.

**Comment by dkim32** [comment]
@EmilyNecciai also don't how how to ensure that it strictly says ``` { Basic {{ 'INKIT_API_TOKEN' | base64_encode }} } ```

**Comment by EmilyNecciai** [comment]
> @EmilyNecciai also don't how how to ensure that it strictly says `{ Basic {{ 'INKIT_API_TOKEN' | base64_encode }} }`. it keeps converting and only shows `Basic Inkit_API_Token`

I just saw this. Hm. I think you'll need a {% raw %} Tag. I'll edit one in and test. :)

**Comment by EmilyNecciai** [comment]
it worked. :) merging!

**Pull request merged**
