### PR TITLE
Remove cross-promotion cards from docs

### PR DESCRIPTION
**Pull request by Bucimis**

### CODE REVIEW

**Comment by Bucimis** [comment]
@EmilyNecciai @zzhaobraze ping on this one

**Comment by EmilyNecciai** [comment]
@Bucimis Is this something that is good to go live at any time?

**Comment by dkim32** [comment]
> @Bucimis Is this something that is good to go live at any time?

@EmilyNecciai we're aiming for the may major release :)

**Comment by EmilyNecciai** [comment]
@dkim32 Great! Thank you!

**Comment by dkim32** [comment]
> > @Bucimis Is this something that is good to go live at any time?
> 
> @EmilyNecciai we're aiming for the may major release :)

i lied. i got this mixed up with the roku docs. this is good to go!

**Pull request merged**
