### PR TITLE
Bluedot integration documentation

### PR DESCRIPTION
**Pull request by toroduque**
# Pull Request/Issue Resolution

**Description of Change:**
> Adding Bluedot documentation

<details>
<summary>PR Checklist</summary>

- [ X ] Check that all links work!
- [ X ] Ensure you have completed [our CLA](https://www.braze.com/docs/cla/).
</details>

### CODE REVIEW

**Comment by toroduque** [comment]
Hi @KellieHawks, I've already signed the Contributor License Agreement but the `cla-bot` doesn't seem to like it, am I missing something?

**Comment by KellieHawks** [comment]
@cla-bot check

**Comment by KellieHawks** [comment]
Hey @toroduque, thanks for contributing! 
Our CLA-bot sometimes has a mind of its own, I just verified that you signed our CLA, so you should be good. The documentation team will work on reviewing your PR today.

**Comment by toroduque** [comment]
@KellieHawks Thanks!

**Comment by KellieHawks** [comment]
Hello @toroduque, on this PR do you mind checking the "Allow edits from maintainers" checkbox? This will allow the braze docs team to make edits to your pull request directly instead of having to push PRs to you forked repo. 

Screen Shot 2020-06-18 at 5 47 08 PM

Thanks in advance!

**Comment by toroduque** [comment]
Hi @KellieHawks I couldn't find that option, I've contacted support and this was their answer:

"_When the source repository of a pull request, belongs to an organization  we disable this option due to complexity around enforcing write permissions for that organization and the target repository's organization._"

Let me know if there's anything I can do

**Comment by KellieHawks** [comment]
@toroduque, I see. Thanks for bearing with us as we get our partner documentation process ironed out. Since I do not have write permissions, I have created a new PR with the appropriate changes. I will tag you in it for visibility. Right now we are waiting on the partner team to finish creating your partnership tile and will add this info to our repo once we get that confirmation. Thanks!
The Braze Documentation Team.

**Pull request closed without merging**
