### PR TITLE
Update integration.md

### PR DESCRIPTION
**Pull request by BrendanJMurray**
# Pull Request/Issue Resolution

**Description of Change:**
I found a broken link and was able to find the commit that broke it.

The link was updated in this commit but not in documentation: https://github.com/Appboy/appboy-ios-sdk/commit/6f7cce31c1d6e57783b3d83f0718a65c2b9e2380#diff-da1b1be0a603d0e830ef7c12d19a84bd

 Note that it originally highlighted some lines which are no longer accurate; I'll leave it up to you if you want to update that

### Is this change associated with a Braze feature/product release?
- [ ] Yes (__Insert Feature Release Date Here__)
- [x] No

> If yes, please note the date of the feature release.

---
---

<details>
<summary>PR Checklist</summary>

- [ ] Check that all links work!
- [ ] Ensure you have completed [our CLA](https://www.braze.com/docs/cla/).
- [ ] Tag @Timothy-Kim and @KellieHawks as a reviewer when your work is _done and ready to be reviewed for merge_.
- [ ] Tag others as Reviewers as necessary.
- [ ] If you have modified any links, be sure to add redirects to `config/nginx.conf.erb`.

</details>

<details>
<summary>Writing & Style Quick Tips</summary>

- Use the formatting shown on the [Styling Test Page](https://github.com/Appboy/braze-docs/blob/develop/_docs/_home/styling_test_page.md) to create unique templates and vehicles for your information.
- Use Action verbs!
- Capitalize proper nouns, unique Braze tools and features, custom Braze channels, and all Header titles.
- Redirect when necessary!
- Always speak to the Braze customer - refer to them as “you”, whether they are an Engineer/Developer, a Marketer, or an Admin.
- On Voice: You should aim to be a Friendly Professor. Imagine, if you will, the smartest, but also kindest professor you had. You know, the one who showed you your potential and tested you, but also went slowly in class so you could take great notes and learn some things? Don't be too peppy, but don't be formal. You’re not selling anything - you’re instructing and informing and enabling.

_Consult the [Docs Text Formatting Guide](https://github.com/Appboy/braze-docs/wiki/Special-Formatting) and the [Docs Writing Style Guide & Best Practices](https://github.com/Appboy/braze-docs/wiki/Writing-Style-Guide-&-Best-Practices) for more details._

</details>

<details>
<summary>ATTENTION: For PR Reviewers</summary>

- [ ] Read our [Reviewing a PR page](https://github.com/Appboy/braze-docs/wiki/Reviewing-a-PR) for more on our reviewing suggestions.
- [ ] Preview all changes in the linked Heroku environment (click `View deployment` button below, then "Docs". A `502` error just means you should refresh until you see the Docs Home page.
</details>

---
---

### CODE REVIEW

**Comment by KellieHawks** [comment]
Hey @BrendanJMurray, thanks for contributing to the Braze-Docs repo! 

We appreciate the time you took to hunt down that correct link and would love to commit your link edit!  Do you mind signing our [Contribution License Agreement](https://www.braze.com/docs/cla/)?

Thanks!
The Braze Docs Team

**Comment by BrendanJMurray** [comment]
Thanks for taking a look at this @KellieHawks, I signed this already but I'm imaging if I get the fields correct that your @cla-bot will update the label here programatically.

Am I inputting one of these incorrectly? (leaving the bottom 2 out of this screenshot)

image

**Comment by KellieHawks** [comment]
@cla-bot check

**Comment by KellieHawks** [comment]
> Thanks for taking a look at this @KellieHawks, I signed this already but I'm imaging if I get the fields correct that your @cla-bot will update the label here programatically.
> 
> Am I inputting one of these incorrectly? (leaving the bottom 2 out of this screenshot)
> 
> image

Hey @BrendanJMurray, thanks for being patient, the CLA bot verified you have signed it. You should be good. Thanks again for contributing!

- The Braze Docs Team

**Comment by BrendanJMurray** [comment]
Thanks @KellieHawks!

**Pull request merged**
